Application\Entity\ParticipantEntity:
    properties:
        name:
            - NotBlank:
                message: 'Name cannot be blank!'
                groups: [ newAndEdit ]
        email:
            - NotBlank:
                message: 'Email cannot be blank!'
                groups: [ newAndEdit ]
            - Email:
                message: 'Invalid email address!'
                groups: [ newAndEdit ]
        via:
            - NotBlank:
                message: 'Via cannot be blank!'
                groups: [ newAndEdit ]

Application\Entity\ProfileEntity:
    properties:
        firstName:
            - NotBlank:
                message: 'First name cannot be blank!'
                groups: [ newAndEdit ]

Application\Entity\RoleEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: role
            message: 'This role already exists!'
            groups: [ newAndEdit ]
    properties:
        name:
            - NotBlank:
                message: 'Name cannot be blank!'
                groups: [ newAndEdit ]
        role:
            - NotBlank:
                message: 'Role cannot be blank!'
                groups: [ newAndEdit ]

Application\Entity\UserEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: 'An user with this email already exists!'
            groups: [ new, edit, register, settings ]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: 'An user with this username already exists!'
            groups: [ new, edit, register, settings ]
    properties:
        username:
            - NotBlank:
                message: 'Username cannot be blank!'
                groups: [ new, edit, register, settings ]
        email:
            - NotBlank:
                message: 'Email cannot be blank!'
                groups: [ new, edit, register, settings, resetPasswordRequest ]
            - Email:
                message: 'Invalid email address'
                groups: [ new, edit, register, settings, resetPasswordRequest ]
        plainPassword:
            - NotBlank:
                message: 'Password cannot be blank!'
                groups: [ new, register, settingsPassword, resetPasswordReset ]
        profile:
            - Valid: ~

Application\Entity\WinnerEntity:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: participant
            message: 'This participant is already an winner!'
            groups: [ newAndEdit ]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: entry
            message: 'This entry is already an winner!'
            groups: [ newAndEdit ]
    properties:
        place:
            - NotBlank:
                message: 'Place cannot be blank!'
                groups: [ newAndEdit ]
